spring.application.name=Testing-App

#DB configuration(In-memory db configuration)
spring.datasource.url=jdbc:postgresql://localhost:5432/springTestDb?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=#Pawani30
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Not needed
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#We are going to use all of this to write unit test for persistence layer(consists of Repository and Entity).Unit tests for the Repository because we dont have to write any unit test for entity because it does not contain any methods any business logic and it is simple POJO classes and we dont have to write any unit tests for POJO classes and inside Repository also we are going to write the test cases for findByEmail method only as EmployeeRepository is extended by JpaRepository which contains a lot of methods that are already tested by developers at spring boot and thats why the methods are in production so we dont have to test the methods present inside the JpaRepository getById,save,delete method.We have to write test cases for findByEmail because they are created by us and for checking the methods are running as expected or not,maybe you are creating some @Query methods or creating some JPQL methods SHOULD BE considered for TESTING.We can write different  test cases for one method findByEmail method,this one method can contain many test cases if you want for different use cases.
#Go to Employee Repository because we have to write test cases for repository and do cmd+shift+T or Ctrl+shift+T and click on create new Test